CREATE TABLE tb_expo (
    id VARCHAR(36) PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    started_day VARCHAR(20) NOT NULL,
    finished_day VARCHAR(20) NOT NULL,
    location TEXT NOT NULL,
    cover_image TEXT,
    x VARCHAR(15) NOT NULL,
    y VARCHAR(15) NOT NULL,
    application_person BIGINT NOT NULL,
    yesterday_application_person BIGINT NOT NULL
);

CREATE TABLE tb_training_program (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(50) NOT NULL,
    started_at VARCHAR(20) NOT NULL,
    ended_at VARCHAR(20) NOT NULL,
    category VARCHAR(255) NOT NULL,
    expo_id VARCHAR(36),
    CONSTRAINT fk_training_program_expo
        FOREIGN KEY (expo_id) REFERENCES tb_expo (id) ON DELETE CASCADE
);

CREATE TABLE tb_standard_program (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(50) NOT NULL,
    started_at VARCHAR(20) NOT NULL,
    ended_at VARCHAR(20) NOT NULL,
    expo_id VARCHAR(36),
    CONSTRAINT fk_standard_program_expo
        FOREIGN KEY (expo_id) REFERENCES tb_expo (id) ON DELETE CASCADE
);
