CREATE TABLE tb_preregister_session (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    expo_id VARCHAR(36) NOT NULL REFERENCES tb_expo (id) ON DELETE CASCADE,
    title VARCHAR(50) NOT NULL,
    started_at TIMESTAMP WITH TIME ZONE NOT NULL,
    ended_at TIMESTAMP WITH TIME ZONE NOT NULL,
    place TEXT NOT NULL,
    capacity INTEGER NOT NULL CHECK (capacity > 0),
    waiting_capacity INTEGER NOT NULL CHECK (waiting_capacity >= 0),
    closed BOOLEAN NOT NULL,
    revision BIGINT NOT NULL DEFAULT 1 CHECK (revision > 0),
    CONSTRAINT preregister_session_period CHECK (ended_at > started_at)
);

CREATE INDEX preregister_session_expo ON tb_preregister_session (expo_id, started_at, id);
